### ISSUE TITLE
How to get slide value when hover slide? 

### ISSUE THREAD

**Issue by yujinqiu** [buh/CompactSlider#6]
Hi, 
I want to add preview video just like Youtube. As you can see if you hover you mouse over the slider, Youtube show an thumbnails and current time.  to support this feature, I think slider should get slide current value when hover.  
How can CompactSlider achieve this ? 

<img width="523" alt="image" src="https://user-images.githubusercontent.com/785405/197389276-0301a2ac-7bc4-4661-aebe-41ff050b1ffa.png">

**Comment by buh** [comment]
Hi @yujinqiu!
The `CompactSliderState` will help you to track the slider state, please check [docs here](https://github.com/buh/CompactSlider/blob/main/Usage.md#advanced-layout) and [the demo project](https://github.com/buh/CompactSlider/blob/main/CompactSliderDemo/Shared/AdvancedView.swift).
