### ISSUE TITLE
Remove the Rule Indicator

### ISSUE THREAD

**Issue by jhonsabowsla** [buh/CompactSlider#9]
how can i remove the lines that seems like a rule ?

**Comment by buh** [comment]
Slider doesn't support this yet, but it's a good question. I will make an update.
I wonder if this is needed for the iOS app?

**Comment by buh** [comment]
Fixed in v.1.1.5

**Comment by buh** [comment]
I thought it could be also useful if the step size could be very small and it doesn't make any sense to show it.
